import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers"
import {ClerkProvider} from "@clerk/nextjs"
import {Toaster} from "sonner"


const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// src/app/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider> 
    <html lang="en" className="mdl-js">
      
      <body className={dmSans.className}>
        <Providers>
          <div className="root-layout">
            {children}
          </div>
          <Toaster richColors closeButton/>
        </Providers>
      </body>
    </html>
    </ClerkProvider> 

  )
}